### ISSUE TITLE
open Maccy crash

### ISSUE THREAD

**Issue by gauseen** [p0deje/Maccy#1048]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

All versions greater than 2.

### macOS Version

15.3 (24D60)

### Maccy Settings

```Shell
~ defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "474 409 620 398 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "529 642 544 197 0 0 1512 944 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2025-02-08 03:31:08 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.png",
        "public.rtf",
        "public.tiff",
        "public.utf8-plain-text",
        "public.html"
    );
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    );
    imageMaxHeight = 0;
    maxMenuItemLength = 0;
    maxMenuItems = 0;
    menuIcon = scissors;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = cursor;
    previewDelay = 0;
    removeFormattingByDefault = 1;
    searchMode = exact;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showTitle = 1;
    sortBy = lastCopiedAt;
    windowSize = "[450,800]";
}
```

### Description

After double-clicking the Maccy app, the Maccy icon in the upper right corner of the computer flickers and then disappears, making it impossible to use Maccy.

**Comment by p0deje** [comment]
Hmm, can you try backing up the following folder, then removing it and restarting Maccy? It would clear your database, but the problem should be fixed. 

```
~/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/
```

**Comment by gauseen** [comment]
> Hmm, can you try backing up the following folder, then removing it and restarting Maccy? It would clear your database, but the problem should be fixed.
> 
> ```
> ~/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/
> ```

![Image](https://github.com/user-attachments/assets/e491125e-4106-41f6-b4da-2138c7d40cb5)

Thank you for your response. I tried deleting the Maccy files, but the app still won't open and crashes immediately.

**Comment by p0deje** [comment]
Hmm, can you try removing the folder `~/Library/Containers/org.p0deje.Maccy` completely?

**Comment by youtextme** [comment]
On Maccy “open Maccy crash”: keep Maccy for paste history if it’s still useful — add free Raycast on ⌥Space so Clipboard History + launcher share one surface for a week. Buy Raycast Pro only after the launcher layer clearly beats juggling two apps; free-first, no rip-out required.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
