### ISSUE TITLE
Ability to paste into Maccy search?

### ISSUE THREAD

**Issue by Stickyhavr** [p0deje/Maccy#192]
Hello,
Hopefully this doesn't already exist in another ticket. I tried to search and didn't see anything.

When I try to paste into Maccy's search bar I get a "donk" error sound and then the Maccy window hides itself. It would be nice to be able to start a search based on what's in the clipboard so you don't have to type it again. This doesn't come up that often but when it does it always surprises me, so I thought I'd ask about it.

**Comment by p0deje** [comment]
Fixed in 40efe5b4da6b182b71d8b55a4643fff7bdb4d03a

**Comment by Stickyhavr** [comment]
Can we still comment on a closed issue? Will you still see this message? I'm not sure. I'll post here but if I don't get a response in a few days, I'll post a new item instead.

First of all, thanks for adding in the paste into search functionality! Just wanted to provide some feedback about the new version 18.2. The way it is implemented currently works fine for my needs (once I figured out how it works), but I just wanted to mention a few things that you might want to refine in the future:

1) I love that you can just paste immediately without giving focus to the search bar! However, that may be unintuitive to some users. Is there a way to make the cursor show up in the search bar by default? Because otherwise some users may wonder what is the correct way to give focus to the search bar before you paste?  

2) On that same note, giving focus with the mouse (by clicking) does not work. If I try to paste after that, I just get the "donk" error sound. This is not a huge issue once I realized I didn't need to give it focus. But just letting you know.

3) Also, if you type any characters and then paste, the paste replaces anything you already typed instead of adding it to the end. I think that's fine though, especially because it's just a search box. In fact, at first when I thought I needed to give focus to the search bar I would type any key and then paste, so I was happy that the key I typed first was not included in the search. So no problem, just not what I expected at first.

4) However, that does bring up another question about the ability to edit your search terms. Right now the only key that works in the search bar is backspace. You can't move the cursor left or right with the arrow keys to fix a typo or make a change and the other normal Mac behaviors don't work either, like moving a word at a time (⌘ + arrow key), or the whole line  or (⌥ + arrow key). All of that would probably be overkill for the purposes of the search bar. But just wanted to mention it because if it's not difficult to add and it doesn't take more resources, then it would be more refined to have the search bar act like most text input fields on the Mac. That leads me to the next question:

5) What is the desired behavior when pushing left and right arrows (or tab and shift-tab) when the Maccy menu is showing? On my machine it's inconsistent. Most of the time it tries to move focus to the next (or previous) item in the menu bar (I guess technically that's called the status menu?) and then the window closes immediately. Sometimes though the window stays open. Also, the Maccy menu does not show if you scroll through the status menu items. In other words if the status menu has the focus (either by clicking up there or ctrl+F8) and then I use my arrow keys to move left and right, it skips right over Maccy (and one other app I have, oh and also the Notification Center I just noticed). Not a big deal, but I didn't expect that behavior. I'm not sure how often I would try to get to Maccy that way, but it might be nice if it did work.

6) Lastly, and this is a little off-topic, what is the search logic? It has probably always been this way and I just never noticed but searching finds lots of results that do not contain my query. But the ones that I'm looking for always show up on top, so I guess it's working. Just wondering why all the other results are showing as well?

Sorry for the LONG post. Thanks for all your hard work!

**Comment by p0deje** [comment]
Thank you for all the comments, I'll reply later.

**Comment by p0deje** [comment]
> I love that you can just paste immediately without giving focus to the search bar! However, that may be unintuitive to some users. Is there a way to make the cursor show up in the search bar by default? Because otherwise some users may wonder what is the correct way to give focus to the search bar before you paste?

My idea is that "type to search..." is enough to indicate you can do that. Also, it should be possible to click on the search field and paste (see point below).

> On that same note, giving focus with the mouse (by clicking) does not work. If I try to paste after that, I just get the "donk" error sound. This is not a huge issue once I realized I didn't need to give it focus. But just letting you know.

This needs to be fixed for sure.

> Also, if you type any characters and then paste, the paste replaces anything you already typed instead of adding it to the end. I think that's fine though, especially because it's just a search box. In fact, at first when I thought I needed to give focus to the search bar I would type any key and then paste, so I was happy that the key I typed first was not included in the search. So no problem, just not what I expected at first.

It seems counterintuitive to me because I'd expect paste to append, but as long as it is good for you, let's keep the current behavior.

> However, that does bring up another question about the ability to edit your search terms. Right now the only key that works in the search bar is backspace. You can't move the cursor left or right with the arrow keys to fix a typo or make a change and the other normal Mac behaviors don't work either, like moving a word at a time (⌘ + arrow key), or the whole line or (⌥ + arrow key). All of that would probably be overkill for the purposes of the search bar. But just wanted to mention it because if it's not difficult to add and it doesn't take more resources, then it would be more refined to have the search bar act like most text input fields on the Mac. That leads me to the next question:

Implementing editing in the search field is a little bit more complicated than it looks. The main problem here is that after you change search term, the first matching result should be selected (i.e. have focus). This implies that search field loses focus, so pressing arrow one more time should either remember its last position or start over again from the end of the search term. Implementing this behavior can become even more tricky once we start taking into account Option/Cmd + arrow modifiers, or removing a character and then appending new characters to the search (where the arrow should now begin?).

> What is the desired behavior when pushing left and right arrows (or tab and shift-tab) when the Maccy menu is showing? On my machine it's inconsistent. Most of the time it tries to move focus to the next (or previous) item in the menu bar (I guess technically that's called the status menu?) and then the window closes immediately. Sometimes though the window stays open. Also, the Maccy menu does not show if you scroll through the status menu items. In other words if the status menu has the focus (either by clicking up there or ctrl+F8) and then I use my arrow keys to move left and right, it skips right over Maccy (and one other app I have, oh and also the Notification Center I just noticed). Not a big deal, but I didn't expect that behavior. I'm not sure how often I would try to get to Maccy that way, but it might be nice if it did work.

I wasn't aware of this. It is likely skipping because Maccy status item is not the usual one, but I'll try fixing it.

> Lastly, and this is a little off-topic, what is the search logic? It has probably always been this way and I just never noticed but searching finds lots of results that do not contain my query. But the ones that I'm looking for always show up on top, so I guess it's working. Just wondering why all the other results are showing as well?

I think you enabled fuzzy search in Preferences and it gives you a bunch of results that non-exactly match your search term.

**Comment by p0deje** [comment]
Created #234 to track status item skip. I guess the rest of the issue can be concluded as done.
