### ISSUE TITLE
Arrow keys support

### ISSUE THREAD

**Issue by wqk317** [p0deje/Maccy#287]
sorry, but i want to know, why not support arrow keys, is there a technical bottleneck?

**Comment by wqk317** [comment]
In addition, how do I know if it is my problem or the software problem?

**Comment by wqk317** [comment]
Oh, I see, the focus is on the search box by default. When I enter content in the search box, I can use the arrow keys to select, but , 
- it is not available by default. 
- It is not possible after hiding the search box. 

Is it true that I am the only one?

**Comment by p0deje** [comment]
The focus cannot be kept on the search box because it's kept on the list items, so that you can select them with up/down keys and Enter. What would the arrow keys do in that case?

**Comment by kidonng** [comment]
I guess the OP is asking to focus on the list right after opening the popup (instead of only when you have entered something).

> It is not possible after hiding the search box.

Not sure what this line means (and from my understanding it's not true)

**Comment by p0deje** [comment]
> I guess the OP is asking to focus on the list right after opening the popup (instead of only when you have entered something).

When the popup is opened, the list is already focused so you can press up/down/Enter. Do you see a different behavior?

**Comment by kidonng** [comment]
> When the popup is opened, the list is already focused so you can press up/down/Enter. Do you see a different behavior?

Yes, as I have described above, the list is only focused when you have entered something. (I'm using the latest version of Maccy downloaded via the website, it you are interested.)

**Comment by p0deje** [comment]
Can you record a small video showing how the list is not focused when popup is open?

Thank you,
Alex

**Comment by rvdsteege** [comment]
I'm experiencing the same issue, but this used to work as described in https://github.com/p0deje/Maccy/issues/287#issuecomment-867095626

I'm using the latest Maccy 0.20.1 on the macOS Monterey beta (build `21A5268h`), maybe @wqk317 is also using the beta?

Short screencast (at the start, before searching, I'm pressing the up/down keys but nothing happens 😉):

![htvF9HsxXf](https://user-images.githubusercontent.com/10371164/124240291-e4408b80-db1a-11eb-92d1-964b5329cbe0.gif)

**Comment by p0deje** [comment]
Hm, this looks like a bug and should work correctly.
@wqk317 What OS version do you use?
@rvdsteege Can you share the output of running `defaults read org.p0deje.Maccy`?

**Comment by rvdsteege** [comment]
<details><summary>Sure, here is my config (click).</summary>

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2304,\\"carbonKeyCode\\":9}";
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "1194 977 620 398 0 0 3008 1667 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1192 698 549 591 0 0 3008 1667 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-07-02 07:49:21 +0000";
    SUUpdateRelaunchingMarker = 1;
    avoidTakingFocus = 0;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text"
    );
    hideFooter = 1;
    hideSearch = 0;
    hideTitle = true;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 200;
    hotKey = "command+option+v";
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "net.antelle.keeweb"
    );
    imageMaxHeight = 16;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-02-22-introduce-history-item" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
    };
    pasteByDefault = true;
    removeFormattingByDefault = 1;
    showInStatusBar = 0;
    supressClearAlert = 1;
}
```
</details>

**Comment by p0deje** [comment]
Ah, I see now. The issue is that you have an Option in your popup hotkey, so when Maccy opens it shows "alternate" menu items and the code highlights non-alternate versions. I'll fi it.

**Comment by rvdsteege** [comment]
Tried, but removing the <kbd>Option</kbd> key from the hotkey does not resolve the issue. Default <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd> does not resolve the issue.

**Comment by p0deje** [comment]
It will work fine if you disable "Paste automatically".

**Comment by kidonng** [comment]
> It will work fine if you disable "Paste automatically".

This answers my question, I have that option enabled. However I don't understand why "Paste automatically" interferes with default selection and IMO it shouldn't.

**Comment by p0deje** [comment]
Yes, it is a bug and I need to fix it.

**Comment by rvdsteege** [comment]
> It will work fine if you disable "Paste automatically".

Nope, it doesn't (sorry 😉).

However, I now discovered that first pressing <kbd>Tab</kbd> once, the list is focused and I can use the arrow keys like before (with <kbd>Option</kbd> in hotkey and **Paste automatically** enabled). Something must have changed with macOS 12 Monterey...

**Comment by p0deje** [comment]
@rvdsteege Do you mind trying this build and see if it fixes an issue?
[Maccy.app.zip](https://github.com/p0deje/Maccy/files/6756987/Maccy.app.zip)

**Comment by rvdsteege** [comment]
Wow, thank you for the build! Tried it, but unfortunately it does not resolve the issue.

I'm happy with the <kbd>Tab</kbd> 'trick', but if there's anything I can do/test to fix this then just let me know.

**Comment by p0deje** [comment]
It seems like there are 2 issues here:

1. The issue when an improper item gets highlighted depending on the hotkey. This is the one fixed in the build ☝️.
2. Some issue on Monterey where nothing is highlighted at all. I guess I need to install beta to figure out what is going on.

**Comment by p0deje** [comment]
faa3de2 hasn't really fixed it - my mistake

**Comment by rvdsteege** [comment]
Already noticed https://github.com/p0deje/Maccy/commit/faa3de23489de2dd91d0508d1d9f7372c322bf65 did not resolve the issue and tried fixing the issue myself, but it didn't work out without any Swift knowledge 😉

I can confirm that https://github.com/p0deje/Maccy/commit/e559d575b1ac6a903ca08ec3bc81b71047ac3870 indeed resolves the issue. Thank you @p0deje!

**Comment by p0deje** [comment]
The fix is still bad as it prevents the field from being clicked and used as a regular text field.
