### ISSUE TITLE
Menubar Item keeps disappearing with Sequoia 15

### ISSUE THREAD

**Issue by max-wittig** [p0deje/Maccy#906]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.4

### macOS Version

15.0.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 202;
    "NSWindow Frame SUStatusFrame" = "664 709 400 134 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "554 510 620 398 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "583 487 542 435 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "593 522 542 400 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-01-26 10:24:30 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 1328013295;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.file-url",
        "public.png",
        "public.tiff",
        "public.html",
        "public.rtf"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType"
    );
    menuIcon = maccy;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    suppressClearAlert = 1;
}
```

### Description

After some time randomly Maccy disappears from the Menubar since 15.0.0. It's also not clickable anymore, but can be opened using keyboard shortcuts

![image](https://github.com/user-attachments/assets/04edbff9-9375-452c-b7d9-c70e81ad0883)

Workaround:

1. Activity monitor
2. Quit Maccy
3. Start Maccy

### Steps to Reproduce

Unsure. It's kinda random.

**Comment by p0deje** [comment]
This is fixed in 2.0.1 please upgrade

**Comment by max-wittig** [comment]
This bug is back. Happens sometimes. Any way I can provide logs to find the root cause?

**Comment by p0deje** [comment]
@max-wittig Let's start with a video recording and trying to find the exact steps to reproduce the problem, there is nothing in logs that could help triage this.

**Comment by max-wittig** [comment]
Seems like homebrew downgraded my version? No idea how this happened, but nevermind then

![image](https://github.com/user-attachments/assets/4d7c6f18-dbc0-4700-bec6-a2768715ce01)
